[package]
name = "bevy_mikktspace"
version = "0.12.0-dev"
edition = "2021"
authors = [
    "Benjamin Wasty <benny.wasty@gmail.com>",
    "David Harvey-Macaulay <alteous@outlook.com>",
    "Layl Bongers <LaylBongers@users.noreply.github.com>",
]
description = "Mikkelsen tangent space algorithm"
documentation = "https://docs.rs/bevy"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "Zlib AND (MIT OR Apache-2.0)"
keywords = ["bevy", "3D", "graphics", "algorithm", "tangent"]

[dependencies]
glam = "0.24"
bitflags = "2.3"

[dev-dependencies]
bytemuck = { version = "1.13", features = ["derive"] }

[[example]]
name = "cube_tangents"
